### PR TITLE
Updated overturning tutorial

### PR DESCRIPTION
**Pull request by jetesdal**
I added more examples in the overturning tutorial. Specifically, the remapping using xgcm and retrojecting isopycnal overturning to depth coordinates.

### CODE REVIEW

**Comment by hmkhatri** [comment]
@jetesdal thanks for adding this. This is really cool. 

Interesting to see the huge difference between offline vs online calculation. Can it be that big or is it because offline calculation used a different equation of state?

Also, in the zonal integration of transport term (in density coordinates) to get the overturning, latitude can change for the same `xh`. It would be worth mentioning that one may need to regrid the data to proper latitudes before computing the zonal integration. `xESMF` library may be useful for that.

I am actually doing a similar calculation from NEMO model output. Unfortunately, re-gridding is giving me a hard time and the errors in overturning calculation from the regraded data are huge.

**Comment by jetesdal** [comment]
Hi @hmkhatri! Thanks for your input. I'm glad you find the added analysis useful. Your thoughts on explaining the difference between offline and online calculations are helpful. It's worth looking into the effect of different EoS. I know @jkrasting created a python function that uses the same EoS as in MOM6. So it should be easy to address this. Also, note that I used annual output. Using monthly or higher frequency could help to reduce the difference between offline and online.

I need to think about how to address the zonal integration part. I see your point, but this applies to both the online and offline calculation, right?

**Comment by hmkhatri** [comment]
> Your thoughts on explaining the difference between offline and online calculations are helpful. It's worth looking into the effect of different EoS. I know @jkrasting created a python function that uses the same EoS as in MOM6.

There is already a function for Wright EOS in the cookbook tutorials. See section on potential density and buoyancy calculation (note that `p` variable in the function needs to be set appropriately for `rho0` and `rho2` coordinates)
https://mom6-analysiscookbook.readthedocs.io/en/latest/notebooks/Buoyancy_Geostrophic_shear.html

> Also, note that I used annual output. Using monthly or higher frequency could help to reduce the difference between offline and online.

Yes, using annual mean `T/S` could make a significant difference. In fact, I have done some preliminary tests to see the effect of temporal averaging. I found that we would probably get lower potential density values on the ocean surface if we used yearly `T/S` instead of monthly (see the figure below). I suspect the difference could be even more if we compare density calculated from daily vs annual `T/S`. So, this could be the reason for the difference between offline and online calculations. 

image

> I need to think about how to address the zonal integration part. I see your point, but this applies to both the online and offline calculation, right?

This applies to both online and offline calculation. I was looking at the source code in [xoverturning](https://github.com/raphaeldussin/xoverturning) and couldn't find any regrinding module. I am not sure if overturning calculations use regridding before zonal integration in practice. 

@raphaeldussin @jkrasting could you comment on the last point of regridding?

**Comment by raphaeldussin** [comment]
@jetesdal thank you for this contribution and so sorry for only seeing this now. Somehow the settings of this repo are bad and I only see changes if someone tags me... I'll look at your notebook asap. Regarding the regridding question from @hmkhatri : the overturning is calculated along the model meridional coordinate and in the case of tripolar grids, it lines up quite nicely with regular/mercator types until 60N or so. I have implemented some rotation algo for transports in `xoverturning` to account for the distortion of the grid at high latitudes and it makes the results more noisy at high latitutdes so I typically do not use it.

One need to be super careful with remapping transports as it is easy to miss one cell face and fail to close with respect to continuity. If you think this is something you want to investigate, I would recommend you use my `sectionate` tool and create sections that goes across the basin at a regular latitude interval (say 1 or 2 degree) and use this to compute the overturning.
Keep us posted of your findings.

**Comment by jkrasting** [comment]
@hmkhatri - I would recommend using the implementation of the Wright EOS in the `momlevel` package I've been putting together.  It has more functions to calculate the density derivatives and the thermal/haline expansion/contraction coefficients.  

https://momlevel.readthedocs.io/en/latest/eos.html
https://momlevel.readthedocs.io/en/latest/api/momlevel.eos.wright.html

The `momlevel.derived.calc_rho` [function](https://momlevel.readthedocs.io/en/latest/api/momlevel.derived.html#momlevel.derived.calc_rho) provides an xarray front-end with proper metadata and is Dask-friendly.

Another advantage is that this code is under version control and undergoes unit testing via `pytest`.

To install:  `pip install momlevel`

**Comment by hmkhatri** [comment]
@raphaeldussin thanks for the clarification on the overturning calculation. I guess it is best to stick with the model grid and try not regard meridional transport data.

@jkrasting Thanks. I was not aware of this package.

**Comment by hmkhatri** [comment]
@raphaeldussin Have you see this script (https://github.com/ECCO-GROUP/ECCOv4-py/blob/master/ecco_v4_py/calc_meridional_trsp.py) for computing meridional transport from MITgcm output.

To compute meridional transport, they first identify the grid cells that correspond to particular latitude. Then they add both y-transport and x-transport. I think this is partly because native Uvel and Vvel are not necessarily zonal and meridional. Anyway, this approach does seem to work better than just using meridional transport values. I tried this with NEMO output to compute overturning in sigma-space in North Atlantic (see figure), the overturning does look much cleaner and the issue with changing lat values along `i` is also resolved.
 
image

In [xoverturning](https://github.com/raphaeldussin/xoverturning/blob/main/xoverturning/moc.py), moc calculation only uses `vmo`. Is there a particular reason for that?

cc @jetesdal

**Comment by jetesdal** [comment]
Thanks @hmkhatri for sharing your work with NEMO.

@raphaeldussin obviously knows more about it, but I think that [calcmoc()](https://github.com/raphaeldussin/xoverturning/blob/4aa055be39580e5eef6b4e22cc8693410ee3cf77/xoverturning/moc.py#L10-L29) in `xoverturnng` requires the input dataset to include `umo`. So I assumed there are some option to use `umo` in the calculations. 

I'm not familiar with the NEMO diagnostics. Is the volume transports already in density space or do you do the remapping offline? It would be interesting to see the code that produced the streamfunction you shared and replicate it with MOM6. Although the isopycnal streamfunction from online `rho2` output does not show the kind of noise apparent in your example, it is worth checking if your method produces noticeable differences with MOM6 output. I am still puzzled why there are these large differences between offline and online calculations in MOM6. I have not seen these differences with MOM5 (e.g. ACCESS) output. So maybe it is related to the grid.

I know @gmacgilchrist thought about this too and he also worked with NEMO, so he might be interested in this discussion.

**Comment by raphaeldussin** [comment]
the original goal of `xoverturning` was to consolidate algos found in multiple analysis scripts at GFDL, with their limitations. However, if there is a better algo (and it works with MOM6) then I'm very happy to include it!

**Comment by hmkhatri** [comment]
@jetesdal here is the response to questions.

> I think that [calcmoc()](https://github.com/raphaeldussin/xoverturning/blob/4aa055be39580e5eef6b4e22cc8693410ee3cf77/xoverturning/moc.py#L10-L29) in xoverturnng requires the input dataset to include umo. So I assumed there are some option to use umo in the calculations.

[compute_streamfunction()](https://github.com/raphaeldussin/xoverturning/blob/4aa055be39580e5eef6b4e22cc8693410ee3cf77/xoverturning/moc.py#L106) only takes meridional transport into account. So, `umo` is not included in overturning calculation.

> I'm not familiar with the NEMO diagnostics. Is the volume transports already in density space or do you do the remapping offline?

Data I am working with is only available as monthly means on z-grid. I had to do the offline remapping to density layers using [xgcm transform](https://xgcm.readthedocs.io/en/latest/transform.html). This step is not required for MOM6 as diagnostics are on rho2 levels. 

> Although the isopycnal streamfunction from online rho2 output does not show the kind of noise apparent in your example, it is worth checking if your method produces noticeable differences with MOM6 output. I am still puzzled why there are these large differences between offline and online calculations in MOM6.

I think noise in NEMO output is because I used u/v velocity data on z-grid rather than mass transport diagnostics. Also, my mask of North Atlantic is not very accurate. The figure is an example and is only from one monthly snapshot. Noise might go away with time-averaging and better masking. 

@jetesdal  I should prepare a proper script that explains this calculation step by step with relevant math. It took me some time to understand why adding zonal transport makes sense. Anyway, I am sharing the code with you  on slack. It would be nice to see how this works with MOM6 output.

@raphaeldussin if the method works for MOM6, would it be worth open a discussion thread on `xoverturning` repo?

**Comment by raphaeldussin** [comment]
thanks @jetesdal for this very nice contribution!

**Pull request merged**
