### PR TITLE
typo correction in vorticity budget notebook

### PR DESCRIPTION
**Pull request by hmkhatri**
The merge request is for correcting typos in the second table 2 in the vorticity budget tutorial and correcting a link to documentation.

### CODE REVIEW

**Comment by hmkhatri** [comment]
@raphaeldussin Could you check what is the error is about? I don't understand it. 
I only corrected some typos in the text, so the merge should work without errors.

**Comment by raphaeldussin** [comment]
fixed some rtd stuff, rebase from master and try again

**Comment by hmkhatri** [comment]
> fixed some rtd stuff, rebase from master and try again

Thanks @raphaeldussin. No conflicts and ready to merge now.

**Comment by raphaeldussin** [comment]
@hmkhatri thanks for the updates

**Pull request merged**
